# Generated by Django 3.0.4 on 2020-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255)),
                ('customer_order_number', models.SlugField(max_length=255)),
                ('delivery_postcode', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.SlugField(max_length=255),
        ),
    ]
